
package org.soa.math.dispatch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathDispatchService", targetNamespace = "http://dispatch.math.soa.org/", wsdlLocation = "http://192.168.56.1:9002/?wsdl")
public class MathDispatchService
    extends Service
{

    private final static URL MATHDISPATCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHDISPATCHSERVICE_EXCEPTION;
    private final static QName MATHDISPATCHSERVICE_QNAME = new QName("http://dispatch.math.soa.org/", "MathDispatchService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.1:9002/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHDISPATCHSERVICE_WSDL_LOCATION = url;
        MATHDISPATCHSERVICE_EXCEPTION = e;
    }

    public MathDispatchService() {
        super(__getWsdlLocation(), MATHDISPATCHSERVICE_QNAME);
    }

    public MathDispatchService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHDISPATCHSERVICE_QNAME, features);
    }

    public MathDispatchService(URL wsdlLocation) {
        super(wsdlLocation, MATHDISPATCHSERVICE_QNAME);
    }

    public MathDispatchService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHDISPATCHSERVICE_QNAME, features);
    }

    public MathDispatchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathDispatchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathDispatch
     */
    @WebEndpoint(name = "MathDispatchPort")
    public MathDispatch getMathDispatchPort() {
        return super.getPort(new QName("http://dispatch.math.soa.org/", "MathDispatchPort"), MathDispatch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathDispatch
     */
    @WebEndpoint(name = "MathDispatchPort")
    public MathDispatch getMathDispatchPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dispatch.math.soa.org/", "MathDispatchPort"), MathDispatch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHDISPATCHSERVICE_EXCEPTION!= null) {
            throw MATHDISPATCHSERVICE_EXCEPTION;
        }
        return MATHDISPATCHSERVICE_WSDL_LOCATION;
    }

}
