
package org.soa.virtualmachine.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VirtualMachineControls", targetNamespace = "http://webservice.virtualmachine.soa.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VirtualMachineControls {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startArithmaticServer", targetNamespace = "http://webservice.virtualmachine.soa.org/", className = "org.soa.virtualmachine.webservice.StartArithmaticServer")
    @ResponseWrapper(localName = "startArithmaticServerResponse", targetNamespace = "http://webservice.virtualmachine.soa.org/", className = "org.soa.virtualmachine.webservice.StartArithmaticServerResponse")
    @Action(input = "http://webservice.virtualmachine.soa.org/VirtualMachineControls/startArithmaticServerRequest", output = "http://webservice.virtualmachine.soa.org/VirtualMachineControls/startArithmaticServerResponse")
    public int startArithmaticServer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopServer", targetNamespace = "http://webservice.virtualmachine.soa.org/", className = "org.soa.virtualmachine.webservice.StopServer")
    @ResponseWrapper(localName = "stopServerResponse", targetNamespace = "http://webservice.virtualmachine.soa.org/", className = "org.soa.virtualmachine.webservice.StopServerResponse")
    @Action(input = "http://webservice.virtualmachine.soa.org/VirtualMachineControls/stopServerRequest", output = "http://webservice.virtualmachine.soa.org/VirtualMachineControls/stopServerResponse")
    public int stopServer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
