
package org.soa.virtualmachine.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VirtualMachineControlsService", targetNamespace = "http://webservice.virtualmachine.soa.org/", wsdlLocation = "http://192.168.56.1:8080/SOAVm/VirtualMachineControlsService?wsdl")
public class VirtualMachineControlsService
    extends Service
{

    private final static URL VIRTUALMACHINECONTROLSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIRTUALMACHINECONTROLSSERVICE_EXCEPTION;
    private final static QName VIRTUALMACHINECONTROLSSERVICE_QNAME = new QName("http://webservice.virtualmachine.soa.org/", "VirtualMachineControlsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.1:8080/SOAVm/VirtualMachineControlsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIRTUALMACHINECONTROLSSERVICE_WSDL_LOCATION = url;
        VIRTUALMACHINECONTROLSSERVICE_EXCEPTION = e;
    }

    public VirtualMachineControlsService() {
        super(__getWsdlLocation(), VIRTUALMACHINECONTROLSSERVICE_QNAME);
    }

    public VirtualMachineControlsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIRTUALMACHINECONTROLSSERVICE_QNAME, features);
    }

    public VirtualMachineControlsService(URL wsdlLocation) {
        super(wsdlLocation, VIRTUALMACHINECONTROLSSERVICE_QNAME);
    }

    public VirtualMachineControlsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIRTUALMACHINECONTROLSSERVICE_QNAME, features);
    }

    public VirtualMachineControlsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VirtualMachineControlsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VirtualMachineControls
     */
    @WebEndpoint(name = "VirtualMachineControlsPort")
    public VirtualMachineControls getVirtualMachineControlsPort() {
        return super.getPort(new QName("http://webservice.virtualmachine.soa.org/", "VirtualMachineControlsPort"), VirtualMachineControls.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VirtualMachineControls
     */
    @WebEndpoint(name = "VirtualMachineControlsPort")
    public VirtualMachineControls getVirtualMachineControlsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.virtualmachine.soa.org/", "VirtualMachineControlsPort"), VirtualMachineControls.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIRTUALMACHINECONTROLSSERVICE_EXCEPTION!= null) {
            throw VIRTUALMACHINECONTROLSSERVICE_EXCEPTION;
        }
        return VIRTUALMACHINECONTROLSSERVICE_WSDL_LOCATION;
    }

}
