
package services.arithmatic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdditionServiceService", targetNamespace = "http://arithmatic.services/", wsdlLocation = "http://192.168.56.101:9002/?wsdl")
public class AdditionServiceService
    extends Service
{

    private final static URL ADDITIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDITIONSERVICESERVICE_EXCEPTION;
    private final static QName ADDITIONSERVICESERVICE_QNAME = new QName("http://arithmatic.services/", "AdditionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.101:9002/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDITIONSERVICESERVICE_WSDL_LOCATION = url;
        ADDITIONSERVICESERVICE_EXCEPTION = e;
    }

    public AdditionServiceService() {
        super(__getWsdlLocation(), ADDITIONSERVICESERVICE_QNAME);
    }

    public AdditionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDITIONSERVICESERVICE_QNAME, features);
    }

    public AdditionServiceService(URL wsdlLocation) {
        super(wsdlLocation, ADDITIONSERVICESERVICE_QNAME);
    }

    public AdditionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDITIONSERVICESERVICE_QNAME, features);
    }

    public AdditionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdditionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdditionService
     */
    @WebEndpoint(name = "AdditionServicePort")
    public AdditionService getAdditionServicePort() {
        return super.getPort(new QName("http://arithmatic.services/", "AdditionServicePort"), AdditionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdditionService
     */
    @WebEndpoint(name = "AdditionServicePort")
    public AdditionService getAdditionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://arithmatic.services/", "AdditionServicePort"), AdditionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDITIONSERVICESERVICE_EXCEPTION!= null) {
            throw ADDITIONSERVICESERVICE_EXCEPTION;
        }
        return ADDITIONSERVICESERVICE_WSDL_LOCATION;
    }

}
