
package services.arithmatic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DivisionService", targetNamespace = "http://arithmatic.services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DivisionService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://arithmatic.services/", className = "services.arithmatic.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://arithmatic.services/", className = "services.arithmatic.CalculateResponse")
    public Object calculate(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Object arg1);

}
