
package services.arithmatic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DivisionServiceService", targetNamespace = "http://arithmatic.services/", wsdlLocation = "http://192.168.56.101:9002/?wsdl")
public class DivisionServiceService
    extends Service
{

    private final static URL DIVISIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DIVISIONSERVICESERVICE_EXCEPTION;
    private final static QName DIVISIONSERVICESERVICE_QNAME = new QName("http://arithmatic.services/", "DivisionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.101:9002/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIVISIONSERVICESERVICE_WSDL_LOCATION = url;
        DIVISIONSERVICESERVICE_EXCEPTION = e;
    }

    public DivisionServiceService() {
        super(__getWsdlLocation(), DIVISIONSERVICESERVICE_QNAME);
    }

    public DivisionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIVISIONSERVICESERVICE_QNAME, features);
    }

    public DivisionServiceService(URL wsdlLocation) {
        super(wsdlLocation, DIVISIONSERVICESERVICE_QNAME);
    }

    public DivisionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIVISIONSERVICESERVICE_QNAME, features);
    }

    public DivisionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DivisionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DivisionService
     */
    @WebEndpoint(name = "DivisionServicePort")
    public DivisionService getDivisionServicePort() {
        return super.getPort(new QName("http://arithmatic.services/", "DivisionServicePort"), DivisionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DivisionService
     */
    @WebEndpoint(name = "DivisionServicePort")
    public DivisionService getDivisionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://arithmatic.services/", "DivisionServicePort"), DivisionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIVISIONSERVICESERVICE_EXCEPTION!= null) {
            throw DIVISIONSERVICESERVICE_EXCEPTION;
        }
        return DIVISIONSERVICESERVICE_WSDL_LOCATION;
    }

}
